name: CD
 
on:
  push:
    branches: [ dev ]
 
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to develop
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        password: ${{ secrets.SECRET_PASSWORD }}
        script: 'cd /var/www/backendbootcamp.proshore.eu/backend && ./server_deploy.sh'
